name: Pull Request
on:
  pull_request:
    branches:
      - master
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.2
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.2
        with:
          cmd: lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.2
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.2
        with:
          cmd: test
