name: Pull Request
on:
  pull_request:
    branches:
      - master
jobs:
  checkPackageVersion:
    name: Check package version
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v1.0.0

      - name: Check package version
        uses: EndBug/version-check@v1.1.0
        id: check

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1.0.0

      - name: Yarn install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      
      - name: Lint
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1.0.0

      - name: Yarn install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      
      - name: Test
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test
