name: Release
on:
  push:
    branches:
      - master
jobs:
  publish_package:
    name: Publish npm package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: publish
          auth-token: ${{ secrets.NPM_TOKEN }}
          registry-url: 'registry.npmjs.org'

  publish_storybook:
    name: Publish Storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        with:
          run: deploy-storybook --ci
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

